Repository ess-dmsc/kafka-to-nexus, pull requests merged in 2018-10, with the labels that each got.

#297 Histogram writer for hs00 schema
  README.md
  conan/conanfile.txt
  docs/writer_module_hs00_event_histogram.md
  src/CMakeLists.txt
  src/HDFWriterModule.cpp
  src/HDFWriterModule.h
  src/Source.cpp
  src/schemas/CMakeLists.txt
  src/schemas/hs00/CMakeLists.txt
  src/schemas/hs00/Dimension.cpp
  src/schemas/hs00/Dimension.h
  src/schemas/hs00/Exceptions.cpp
  src/schemas/hs00/Exceptions.h
  src/schemas/hs00/HistogramRecord.cpp
  src/schemas/hs00/HistogramRecord.h
  src/schemas/hs00/Reader.cpp
  src/schemas/hs00/Reader.h
  src/schemas/hs00/Shape.cpp
  src/schemas/hs00/Shape.h
  src/schemas/hs00/Slice.cpp
  src/schemas/hs00/Slice.h
  src/schemas/hs00/Writer.cpp
  src/schemas/hs00/Writer.h
  src/schemas/hs00/WriterTyped.cpp
  src/schemas/hs00/WriterTyped.h
  src/schemas/hs00/WriterUntyped.cpp
  src/schemas/hs00/WriterUntyped.h
  src/tests/CMakeLists.txt
  src/tests/EventHistogramWriterTests.cpp
Labels: enhancement

#305 Update the readme
  README.md
  docs/filewriter_dev_docs.md
  docs/installation-using-ansible.md
  docs/manual-build.md
  docs/writer_module_f142_log_data.md
Labels: documentation

#311 Log message instead of program termination when structure cannot be written to nexus file
  src/CommandHandler.cpp
  src/HDFFile.cpp
  src/HDFFile.h
  src/schemas/NDAr/AreaDetectorWriter.cpp
  src/schemas/ev42/ev42_rw.cpp
  src/schemas/f142/f142_rw.cpp
  src/schemas/senv/FastSampleEnvironmentWriter.cpp
  src/tests/HDFFile.cpp
  src/tests/HDFFileAttributesTest.cpp
  src/tests/HDFFileTestHelper.cpp
Labels: Ready for review

#315 Making log messages consistent
  src/HDFFile.cpp
  src/KafkaW/BrokerSettings.cpp
  src/KafkaW/Producer.cpp
  src/KafkaW/TopicSettings.cpp
  src/Source.cpp
  src/schemas/ev42/ev42_rw.cpp
  src/schemas/ev42/ev42_synth.cpp
  src/schemas/events/schema_amo0.cpp
  src/schemas/f142/f142_rw.cpp
  src/schemas/hs00/WriterTyped.h
Labels: Ready for review
