Repository ess-dmsc/kafka-to-nexus, pull requests merged in 2018-03, with the labels that each got.

#131 Support vector attributes
  README.md
  docs/attributes.md
  docs/groups.md
  src/HDFFile.cxx
  src/HDFFile.h
  src/tests/CMakeLists.txt
  src/tests/HDFFile.cxx
  src/tests/HDFFileAttributesTest.cpp
Labels: enhancement

#142 #141 Added comments from Code Review
  src/CommandHandler.cxx
  src/CommandHandler.h
  src/HDFWriterModule.h
  src/Master.cxx
  src/Master.h
Labels: from code review

#136 Fix long integer bug
  src/HDFFile.cxx
  src/tests/CMakeLists.txt
  src/tests/HDFFile.cxx
  src/tests/HDFFileAttributesTest.cpp
  src/tests/HDFFileTestHelper.cpp
  src/tests/HDFFileTestHelper.h
Labels: bug, high priority

#144 H5cpp in dataset writer
  src/CommandHandler.cxx
  src/HDFFile.cxx
  src/HDFWriterModule.h
  src/h5.cxx
  src/h5.h
  src/schemas/ev42/ev42_rw.cxx
  src/schemas/f142/f142_rw.cxx
Labels: enhancement
