Repository ess-dmsc/kafka-to-nexus, pull requests merged in 2018-11, with the labels that each got.

#332 Optionally write latest LogData value into configurable dataset
  README.md
  src/h5.cpp
  src/h5.h
  src/schemas/f142/WriterArray.h
  src/schemas/f142/WriterScalar.h
  src/schemas/f142/WriterScalarString.cpp
  src/schemas/f142/WriterScalarString.h
  src/schemas/f142/WriterTypedBase.h
  src/schemas/f142/f142_rw.cpp
  src/schemas/f142/f142_rw.h
  src/tests/Schema_f142.cpp
Labels: enhancement

#338 Create HDF links via Nexus structure
  README.md
  src/FileWriterTask.cpp
  src/HDFFile.cpp
  src/HDFFile.h
  src/tests/CommandHandlerTests.cpp
Labels: enhancement

#356 Fix Streamer/Kafka interaction
  src/KafkaW/Consumer.cpp
  src/KafkaW/Consumer.h
  src/Streamer.cpp
  src/h5.cpp
  src/tests/StatusWriterTests.cpp
  src/tests/StreamerTest.cpp
Labels: in progress

#363 Add timeout for system test step in jenkinsfile
  Jenkinsfile
Labels: Ready for review
