Repository ess-dmsc/kafka-to-nexus, pull requests merged in 2019-01, with the labels that each got.

#378 Go Format Yourself
  Jenkinsfile
Labels: in progress

#382 Avoid rebuilding dependencies on every Jenkins build
  conan/conanfile.txt
  src/NeXusDataset.h
  src/schemas/NDAr/AreaDetectorWriter.cpp
  src/schemas/NDAr/AreaDetectorWriter.h
  src/schemas/ev42/ev42_rw.cpp
  src/schemas/ev42/ev42_synth.h
  src/schemas/events/schema_amo0.cpp
  src/schemas/f142/Common.h
  src/schemas/f142/f142_synth.h
  src/schemas/hs00/Reader.cpp
  src/schemas/hs00/Slice.cpp
  src/schemas/hs00/WriterTyped.h
  src/schemas/senv/FastSampleEnvironmentWriter.cpp
  src/schemas/senv/FastSampleEnvironmentWriter.h
  src/tests/FastSampleEnvironmentWriterTests.cpp
  system-tests/test_filewriter.py
Labels: Ready for review

#375 DM-1223 Fixing start&stop timestamp persistance
  src/CommandHandler.cpp
  system-tests/commands/commandwithnostoptime.json
  system-tests/commands/commandwithstoptime.json
  system-tests/config-files/file_writer_config_stop_command.ini
  system-tests/conftest.py
  system-tests/docker-compose-stop-command.yml
  system-tests/helpers/kafkahelpers.py
  system-tests/helpers/timehelpers.py
  system-tests/test_filewriter_clears_stop_time.py
Labels: bug
